### ISSUE TITLE
user can delete a home

### ISSUE THREAD

**Issue by theonlyrao** [patrickwhardy/the_pivot#11]
As a logged in owner,
when I visit my owner show page,
and I click on "delete" under a particular home,
I see a prompt "Are you sure you want to delete this home?",
and click "Yes, delete home",
then I am taken back to my owner show page,
and that home is no longer on the page,
and I see a message that the home has been deleted.

**Comment by theonlyrao** [comment]
Josh's let's discuss how to integrate the admin's ability to delete a home with a users

**Comment by jwashke** [comment]
Yeah I guess that one is more similar then we realized when distributing the cards. The links and controller actions should probably be the same, just scoping permissions to both the home owner and the admin



On May 12, 2016 at 9:27:33 PM, theonlyrao (notifications@github.com) wrote:

Josh's let's discuss how to integrate the admin's ability to delete a home with a users

**Comment by jwashke** [comment]
You can implement it and just scope it to the home owner and current_admin or I can, just let me know which you would prefer to do.
